"""add user language preference

Revision ID: 5066276d0137
Revises: 8d66749df06b
Create Date: 2026-08-14 22:41:49.489338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5066276d0137'
down_revision = '8d66749df06b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language_preference', sa.String(length=10), nullable=False, server_default='en'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('language_preference')

    # ### end Alembic commands ###
